### PR TITLE
Update the libraries page

### PR DESCRIPTION
**Pull request by fsteeg**
See commits for details. Hope the move from services to libraries makes sense.

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Thanks!
From my perspective, I still see a difference between a library (a software component that can be used to make end-user software) and a reconciliation service (something a user can directly run / host to expose a reconciliation service). So that was the spirit between the existing separation. But no problem if you prefer it that way.

**Comment by fsteeg** [comment]
Right, I guess I see it more from a data provider perspective: what tools can I use to make my data available for reconciliation? But I see your point, so maybe we change the libraries.md as suggested here but leave the services.md untouched?

**Comment by wetneb** [comment]
> what tools can I use to make my data available for reconciliation?

Then from that perspective we could break those tools down into two categories: those which will require you to program something to make your service work and those who will not. It could be represented by two different tables, or a column in the table.

Also, a library for the reconciliation protocol could be a client library (like the one I would like to write in Java), not a server one, so it would not really be relevant for someone who wants to make their data available for reconciliation.

**Comment by fsteeg** [comment]
Hm, yes, it's all a little tricky.

>  those which will require you to program something to make your service work and those who will not

That distinction is not always clear cut (e.g. skohub-reconcile, which does not require programming in the strict sense, but is not an end-user tool either). Also it can be hard to assess for us since we're not familiar with all the tools and libraries.

> Also, a library for the reconciliation protocol could be a client library (like the one I would like to write in Java), not a server one, so it would not really be relevant for someone who wants to make their data available for reconciliation.

Right, maybe long term it would make more sense to include the libraries in a dedicated section under each /services and /clients, and remove the /libraries page altogether.

For now though, I've remove the commit that moves the items from /services to /libraries and added a link from /libraries to /services instead, so that people will find them when they look at /libraries. We can always restructure this in the future.

**Review by wetneb — APPROVED** [review]
Sorry for the delay

**Pull request merged**
